# Site settings
title: Twitter trolls strategy to disrupt democracy
description: 'Applied Data Analysis EPFL'
url: 'https://ada-asjl.github.io'
#baseurl: '/jekyll-uno'
baseurl: '/' # change to this to run on github

# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Josh Gerdes'
  email: ahmed.sadllh@gmail.com.com
  twitter_username: joshgerdes
  facebook_username: joshgerdes
  github_username:  asaadal
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
