# Site settings
title: Scriptum Lucis
description: 'Personal Blog'
url: 'http://scriptum-lucis.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Ahmed S'
  email: stillunderconstruction
  twitter_username: stillunderconstruction
  facebook_username: stillunderconstruction
  github_username:  stillunderconstruction
  linkedin_username:  stillunderconstruction

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
